name: Deployment

on:
  push:
    branches:
      - "dev"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore cached files
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.npm
          ./.cache
          ./buildtools/node_modules
        key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
        restore-keys: ${{ runner.os }}-bunny-

    - name: "Setup NodeJS v13"
      uses: actions/setup-node@v2
      with:
        node-version: "13"
        check-latest: true

    - name: "Download NPM packages"
      working-directory: ./buildtools
      run: npm ci

    - name: "Check environmental variables"
      working-directory: ./buildtools
      run: npx gulp check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
        CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}

    - name: "Build everything"
      working-directory: ./buildtools
      run: npx gulp buildAll

    - name: "Rename artifacts"
      working-directory: ./buildtools
      run: npx gulp postBuild
      id: postBuild

    - uses: actions/upload-artifact@v2
      with:
        name: dev-preview-client
        path: |
          build/*-client.zip

    - uses: actions/upload-artifact@v2
      with:
        name: dev-preview-server
        path: |
          build/*-server.zip

    - uses: actions/upload-artifact@v2
      with:
        name: dev-preview-lang
        path: |
          build/lang.zip
